- name: Perform health checks on Cisco Devices
  hosts: cisco_devices
  gather_facts: yes
  connection: network_cli
  tasks:

    - name: Gather IOS facts
      cisco.ios.ios_facts:
      ignore_errors: yes

    - name: Show switch
      cisco.ios.ios_command:
        commands:
          - show switch
      register: switch_output
      ignore_errors: yes

    - name: Show version info
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output
      ignore_errors: yes

    - name: Show process CPU
      cisco.ios.ios_command:
        commands:
          - show process cpu
      register: cpu_output
      ignore_errors: yes

    - name: Show processes CPU
      cisco.ios.ios_command:
        commands:
          - show processes cpu
      register: processes_cpu_output
      ignore_errors: yes

    - name: Show process CPU history
      cisco.ios.ios_command:
        commands:
          - show process cpu history
      register: cpu_history_output
      ignore_errors: yes

    - name: Show CPU usage
      cisco.ios.ios_command:
        commands:
          - show cpu usage
      register: cpu_usage_output
      ignore_errors: yes

    - name: Show CPU
      cisco.ios.ios_command:
        commands:
          - show cpu
      register: cpu_general_output
      ignore_errors: yes

    - name: Show processes memory
      cisco.ios.ios_command:
        commands:
          - show processes memory
      register: memory_output
      ignore_errors: yes

    - name: Show CDP neighbors
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors
      register: cdp_neighbors_output
      ignore_errors: yes

    - name: Show detailed CDP neighbors
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors detail
      register: cdp_neighbors_detail_output
      ignore_errors: yes

    - name: Show etherchannel summary
      cisco.ios.ios_command:
        commands:
          - show etherchannel summary
      register: etherchannel_output
      ignore_errors: yes

    - name: Show IP interface brief
      cisco.ios.ios_command:
        commands:
          - show ip int brief
      register: ip_int_brief_output
      ignore_errors: yes

    - name: Show bootflash details
      cisco.ios.ios_command:
        commands:
          - show sup-bootflash:
          - show bootflash:
          - show flash:
          - show sup-bootflash//:
          - show bootflash//:
          - show sup-bootflash://
          - show bootflash://
      register: bootflash_output
      ignore_errors: yes

    - name: Show system resources
      cisco.ios.ios_command:
        commands:
          - show system resources
      register: system_resources_output
      ignore_errors: yes

    - name: Show module information
      cisco.ios.ios_command:
        commands:
          - show module
          - show modules
      register: module_output
      ignore_errors: yes

    - name: Show stack power details
      cisco.ios.ios_command:
        commands:
          - show stack-power detail
          - show stack-power neighbors
      register: stack_power_output
      ignore_errors: yes

    - name: Show VLAN brief
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_brief_output
      ignore_errors: yes

    - name: Show inventory
      cisco.ios.ios_command:
        commands:
          - show inventory
      register: inventory_output
      ignore_errors: yes

    - name: Show power details
      cisco.ios.ios_command:
        commands:
          - show power
          - show environment temperature
          - show power status power-supply 1
          - show power status power-supply 2
          - show power status fan-tray
          - show power used
          - show power total
          - show power inl
          - show power status all
      register: power_output
      ignore_errors: yes

    - name: Show environment details
      cisco.ios.ios_command:
        commands:
          - show environment cooling
          - show environment status
          - sh env all
      register: environment_output
      ignore_errors: yes

    - name: Show redundancy and stackwise-virtual details
      cisco.ios.ios_command:
        commands:
          - show redundancy
          - show redundancy states
          - show stackwise-virtual
          - show stackwise-virtual bandwidth
          - show stackwise-virtual neighbors
          - show stackwise-virtual link
          - show stackwise-virtual switch 1
          - show stackwise-virtual switch 2
      register: redundancy_output
      ignore_errors: yes

    - name: Show running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config_output
      ignore_errors: yes

    - name: Show protocols
      cisco.ios.ios_command:
        commands:
          - show protocols
      register: protocols_output
      ignore_errors: yes

    - name: Show IP route
      cisco.ios.ios_command:
        commands:
          - show ip route
      register: ip_route_output
      ignore_errors: yes

    - name: Show interface status
      cisco.ios.ios_command:
        commands:
          - show interface status
      register: interface_status_output
      ignore_errors: yes

    - name: Show logs and MAC addresses
      cisco.ios.ios_command:
        commands:
          - show mac address
          - show logg
      register: log_output
      ignore_errors: yes

    - name: Show licensing and feature information
      cisco.ios.ios_command:
        commands:
          - show features
          - show vpc
          - show fex
          - show lice sum
      register: features_output
      ignore_errors: yes

    - name: Ensure output directory exists
      file:
        path: output
        state: directory
        mode: '0755'

    - name: Save output to a file for the device
      copy:
        content: |
          Switch Details:
          {% if switch_output.stdout is defined %}
          {% for line in switch_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show switch"
          {% endif %}

          Version:
          {% if version_output.stdout is defined %}
          {% for line in version_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show version"
          {% endif %}

          CPU :
          {% if cpu_output.stdout is defined %}
          {% for line in cpu_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show process cpu"
          {% endif %}

          CPU History :
          {% if cpu_history_output.stdout is defined %}
          {% for line in cpu_history_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show process cpu history"
          {% endif %}

          Memory :
          {% if memory_output.stdout is defined %}
          {% for line in memory_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show processes memory"
          {% endif %}

          CDP Neighbors :
          {% if cdp_neighbors_output.stdout is defined %}
          {% for line in cdp_neighbors_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show cdp neighbors"
          {% endif %}

          CDP Neighbors Detail :
          {% if cdp_neighbors_detail_output.stdout is defined %}
          {% for line in cdp_neighbors_detail_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show cdp neighbors detail"
          {% endif %}

          EtherChannel Summary :
          {% if etherchannel_output.stdout is defined %}
          {% for line in etherchannel_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show etherchannel summary"
          {% endif %}

          IP Interface Brief :
          {% if ip_int_brief_output.stdout is defined %}
          {% for line in ip_int_brief_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show ip int brief"
          {% endif %}

          Bootflash :
          {% if bootflash_output.stdout is defined %}
          {% for line in bootflash_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show bootflash"
          {% endif %}

          System Resources :
          {% if system_resources_output.stdout is defined %}
          {% for line in system_resources_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show system resources"
          {% endif %}

          Module Information :
          {% if module_output.stdout is defined %}
          {% for line in module_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show module"
          {% endif %}

          Stack Power Details :
          {% if stack_power_output.stdout is defined %}
          {% for line in stack_power_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show stack-power detail"
          {% endif %}

          VLAN Brief :
          {% if vlan_brief_output.stdout is defined %}
          {% for line in vlan_brief_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show vlan brief"
          {% endif %}

          Inventory :
          {% if inventory_output.stdout is defined %}
          {% for line in inventory_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show inventory"
          {% endif %}

          Power :
          {% if power_output.stdout is defined %}
          {% for line in power_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show power"
          {% endif %}

          Environment :
          {% if environment_output.stdout is defined %}
          {% for line in environment_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show environment status"
          {% endif %}

          Redundancy :
          {% if redundancy_output.stdout is defined %}
          {% for line in redundancy_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show redundancy"
          {% endif %}

          Running Config :
          {% if running_config_output.stdout is defined %}
          {% for line in running_config_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show running-config"
          {% endif %}

          Protocols :
          {% if protocols_output.stdout is defined %}
          {% for line in protocols_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show protocols"
          {% endif %}

          IP Route :
          {% if ip_route_output.stdout is defined %}
          {% for line in ip_route_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show ip route"
          {% endif %}

          Interface Status :
          {% if interface_status_output.stdout is defined %}
          {% for line in interface_status_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show interface status"
          {% endif %}

          Log :
          {% if log_output.stdout is defined %}
          {% for line in log_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show log"
          {% endif %}

          Licensing and Features :
          {% if features_output.stdout is defined %}
          {% for line in features_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show features"
          {% endif %}


        dest: "output/{{ ansible_facts['net_hostname'] }}_health_check_output.txt"
        mode: '0644'

    - name: Show all gathered facts
      debug:
        var: ansible_facts
