- name: Perform health checks on Cisco Devices
  hosts: cisco_devices
  gather_facts: no
  connection: network_cli
  tasks:

    - name: Gather IOS facts
      cisco.ios.ios_facts:
      ignore_errors: yes

    - name: Show version info
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output
      ignore_errors: yes

    - name: Show CPU utilization
      cisco.ios.ios_command:
        commands:
          - show process cpu
      register: cpu_output
      ignore_errors: yes

    - name: Show process CPU history
      cisco.ios.ios_command:
        commands:
          - show process cpu history
      register: cpu_history_output
      ignore_errors: yes

    - name: Show memory usage
      cisco.ios.ios_command:
        commands:
          - show processes memory
      register: memory_output
      ignore_errors: yes

    - name: Show CDP neighbors
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors
      register: cdp_neighbors_output
      ignore_errors: yes

    - name: Show detailed CDP neighbors
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors detail
      register: cdp_neighbors_detail_output
      ignore_errors: yes

    - name: Show etherchannel summary
      cisco.ios.ios_command:
        commands:
          - show etherchannel summary
      register: etherchannel_output
      ignore_errors: yes

    - name: Show IP interface brief
      cisco.ios.ios_command:
        commands:
          - show ip int brief
      register: ip_int_brief_output
      ignore_errors: yes

    - name: Show VLAN brief
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_brief_output
      ignore_errors: yes

    - name: Show inventory
      cisco.ios.ios_command:
        commands:
          - show inventory
      register: inventory_output
      ignore_errors: yes

    - name: Show power
      cisco.ios.ios_command:
        commands:
          - show power
      register: power_output
      ignore_errors: yes

    - name: Show power inline
      cisco.ios.ios_command:
        commands:
          - show power inline
      register: power_inline_output
      ignore_errors: yes

    - name: Show stack information
      cisco.ios.ios_command:
        commands:
          - show stack
      register: stack_output
      ignore_errors: yes

    - name: Show running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config_output
      ignore_errors: yes

    - name: Show protocols
      cisco.ios.ios_command:
        commands:
          - show protocols
      register: protocols_output
      ignore_errors: yes

    - name: Show IP route
      cisco.ios.ios_command:
        commands:
          - show ip route
      register: ip_route_output
      ignore_errors: yes

    - name: Show interface status
      cisco.ios.ios_command:
        commands:
          - show interface status
      register: interface_status_output
      ignore_errors: yes

    - name: Show CDP neighbors (again, shorter command)
      cisco.ios.ios_command:
        commands:
          - show cdp neigh
      register: cdp_neighbors_short_output
      ignore_errors: yes
    
    - name: Ensure output directory exists
      file:
        path: output
        state: directory
        mode: '0755'

    - name: Save output to a file for the device
      copy:
        content: |
          Version Output:
          {% for line in version_output.stdout %}
          {{ line }}
          {% endfor %}
          
          CPU Output:
          {% for line in cpu_output.stdout %}
          {{ line }}
          {% endfor %}
          
          CPU History Output:
          {% for line in cpu_history_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Memory Output:
          {% for line in memory_output.stdout %}
          {{ line }}
          {% endfor %}
          
          CDP Neighbors Output:
          {% for line in cdp_neighbors_output.stdout %}
          {{ line }}
          {% endfor %}
          
          CDP Neighbors Detail Output:
          {% for line in cdp_neighbors_detail_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Etherchannel Output:
          {% for line in etherchannel_output.stdout %}
          {{ line }}
          {% endfor %}
          
          IP Interface Brief Output:
          {% for line in ip_int_brief_output.stdout %}
          {{ line }}
          {% endfor %}
          
          VLAN Brief Output:
          {% for line in vlan_brief_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Inventory Output:
          {% for line in inventory_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Power Output:
          {% for line in power_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Power Inline Output:
          {% for line in power_inline_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Stack Output:
          {% for line in stack_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Running Config Output:
          {% for line in running_config_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Protocols Output:
          {% for line in protocols_output.stdout %}
          {{ line }}
          {% endfor %}
          
          IP Route Output:
          {% for line in ip_route_output.stdout %}
          {{ line }}
          {% endfor %}
          
          Interface Status Output:
          {% for line in interface_status_output.stdout %}
          {{ line }}
          {% endfor %}
          
          CDP Neighbors Short Output:
          {% for line in cdp_neighbors_short_output.stdout %}
          {{ line }}
          {% endfor %}
          
        dest: "output/{{ inventory_hostname }}_health_check_output.txt"
        mode: '0644'
