- name: Perform health checks on Cisco Devices
  hosts: cisco_devices
  gather_facts: yes
  connection: network_cli
  tasks:

    - name: Gather IOS facts
      cisco.ios.ios_facts:
      ignore_errors: yes

    - name: Show version info
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output
      ignore_errors: yes

    - name: Show CPU utilization
      cisco.ios.ios_command:
        commands:
          - show process cpu
      register: cpu_output
      ignore_errors: yes

    - name: Show process CPU history
      cisco.ios.ios_command:
        commands:
          - show process cpu history
      register: cpu_history_output
      ignore_errors: yes

    - name: Show memory usage
      cisco.ios.ios_command:
        commands:
          - show processes memory
      register: memory_output
      ignore_errors: yes

    - name: Show CDP neighbors
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors
      register: cdp_neighbors_output
      ignore_errors: yes

    - name: Show detailed CDP neighbors
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors detail
      register: cdp_neighbors_detail_output
      ignore_errors: yes

    - name: Show etherchannel summary
      cisco.ios.ios_command:
        commands:
          - show etherchannel summary
      register: etherchannel_output
      ignore_errors: yes

    - name: Show IP interface brief
      cisco.ios.ios_command:
        commands:
          - show ip int brief
      register: ip_int_brief_output
      ignore_errors: yes

    - name: Show VLAN brief
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_brief_output
      ignore_errors: yes

    - name: Show inventory
      cisco.ios.ios_command:
        commands:
          - show inventory
      register: inventory_output
      ignore_errors: yes

    - name: Show power
      cisco.ios.ios_command:
        commands:
          - show power
      register: power_output
      ignore_errors: yes

    - name: Show power inline
      cisco.ios.ios_command:
        commands:
          - show power inline
      register: power_inline_output
      ignore_errors: yes

    - name: Show stack information
      cisco.ios.ios_command:
        commands:
          - show stack
      register: stack_output
      ignore_errors: yes

    - name: Show running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config_output
      ignore_errors: yes

    - name: Show protocols
      cisco.ios.ios_command:
        commands:
          - show protocols
      register: protocols_output
      ignore_errors: yes

    - name: Show IP route
      cisco.ios.ios_command:
        commands:
          - show ip route
      register: ip_route_output
      ignore_errors: yes

    - name: Show interface status
      cisco.ios.ios_command:
        commands:
          - show interface status
      register: interface_status_output
      ignore_errors: yes

    - name: Show CDP neighbors (again, shorter command)
      cisco.ios.ios_command:
        commands:
          - show cdp neigh
      register: cdp_neighbors_short_output
      ignore_errors: yes
    
    - name: Ensure output directory exists
      file:
        path: output
        state: directory
        mode: '0755'

    - name: Save output to a file for the device
      copy:
        content: |
          Version Output:
          {% if version_output.stdout is defined %}
          {% for line in version_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show version"
          {% endif %}
          
          CPU Output:
          {% if cpu_output.stdout is defined %}
          {% for line in cpu_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show process cpu"
          {% endif %}
          
          CPU History Output:
          {% if cpu_history_output.stdout is defined %}
          {% for line in cpu_history_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show process cpu history"
          {% endif %}
          
          Memory Output:
          {% if memory_output.stdout is defined %}
          {% for line in memory_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show processes memory"
          {% endif %}
          
          CDP Neighbors Output:
          {% if cdp_neighbors_output.stdout is defined %}
          {% for line in cdp_neighbors_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show cdp neighbors"
          {% endif %}
          
          CDP Neighbors Detail Output:
          {% if cdp_neighbors_detail_output.stdout is defined %}
          {% for line in cdp_neighbors_detail_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show cdp neighbors detail"
          {% endif %}
          
          Etherchannel Output:
          {% if etherchannel_output.stdout is defined %}
          {% for line in etherchannel_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show etherchannel summary"
          {% endif %}
          
          IP Interface Brief Output:
          {% if ip_int_brief_output.stdout is defined %}
          {% for line in ip_int_brief_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show ip int brief"
          {% endif %}
          
          VLAN Brief Output:
          {% if vlan_brief_output.stdout is defined %}
          {% for line in vlan_brief_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show vlan brief"
          {% endif %}
          
          Inventory Output:
          {% if inventory_output.stdout is defined %}
          {% for line in inventory_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show inventory"
          {% endif %}
          
          Power Output:
          {% if power_output.stdout is defined %}
          {% for line in power_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show power"
          {% endif %}
          
          Power Inline Output:
          {% if power_inline_output.stdout is defined %}
          {% for line in power_inline_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show power inline"
          {% endif %}
          
          Stack Output:
          {% if stack_output.stdout is defined %}
          {% for line in stack_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show stack"
          {% endif %}
          
          Running Config Output:
          {% if running_config_output.stdout is defined %}
          {% for line in running_config_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show running-config"
          {% endif %}
          
          Protocols Output:
          {% if protocols_output.stdout is defined %}
          {% for line in protocols_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show protocols"
          {% endif %}
          
          IP Route Output:
          {% if ip_route_output.stdout is defined %}
          {% for line in ip_route_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show ip route"
          {% endif %}
          
          Interface Status Output:
          {% if interface_status_output.stdout is defined %}
          {% for line in interface_status_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show interface status"
          {% endif %}
          
          CDP Neighbors Short Output:
          {% if cdp_neighbors_short_output.stdout is defined %}
          {% for line in cdp_neighbors_short_output.stdout %}
          {{ line }}
          {% endfor %}
          {% else %}
          No output from "show cdp neigh"
          {% endif %}

        dest: "output/{{ ansible_facts['net_hostname'] }}_health_check_output.txt"
        mode: '0644'

    - name: Show all gathered facts
      debug:
        var: ansible_facts
