[defaults]

[cisco_devices]
172.22.0.5 = 172.22.0.5 ansible_user=admin ansible_ssh_pass=password
172.22.0.12 = 172.22.0.12 ansible_user=admin ansible_ssh_pass=password
172.22.0.34 = 172.22.0.34 ansible_user=admin ansible_ssh_pass=password
172.22.0.78 = 172.22.0.78 ansible_user=admin ansible_ssh_pass=password
devnetsandboxiosxe.cisco.com = devnetsandboxiosxe.cisco.com ansible_user=admin ansible_ssh_pass=password

