- name: Read and Print a Text File
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Read the text file
      slurp:
        src: input/HO04I4_health_check_output.txt
      register: file_content

    - name: Decode the file
      set_fact:
        decoded_file: "{{ file_content['content'] | b64decode }}"

    - name: Extract Switch Model
      set_fact:
        switch_model: "{{ decoded_file | regex_search('(?<=cisco\\s)(?:WS-|CS-|CISCO\\s*)?[A-Z]{1,3}\\d{3,4}[A-Z]*[-\\dA-Z]*', '\\0') | join('') }}"
        board_id: "{{ decoded_file | regex_search('(?<=Processor board ID )\\S+') }}"
        uptime_info: "{{ decoded_file | regex_search('(?m)^.*uptime.*$')}}"
        hostname: "{{ decoded_file | regex_search('(?m)^.*uptime.*$') | regex_search('^\\w+') }}"
        vlan_ip: "{{ decoded_file | regex_search('^Vlan\\d{2,3}\\s+(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})', multiline=True) | default('unknown') | join('') }}"
        switch_version: "{{ decoded_file | regex_search('Cisco IOS Software.*', multiline=True) | regex_search('Version\\s+(\\d+\\.\\d+(\\(\\d+\\))?(\\.\\d+)?([A-Za-z]\\d*)?)', '\\1') | join('') }}"
        system_image: "{{ decoded_file | regex_search('(?:flash|bootflash):([^\\s]+\\.bin)', '\\1') | join('') }}"
        cpu_util: "{{ decoded_file | regex_findall('.*CPU\\s+utilization.*$', multiline=True) }}"
        inventory_data: "{{ decoded_file | regex_findall('^.*(?:NAME|DESCR|PID|VID|SN).*', multiline=True) | select('search', '.*(?:NAME|DESCR|PID|VID|SN).*.*(?:NAME|DESCR|PID|VID|SN).*') }}"

    

    - name: Extract cisco_info
      set_fact:
        cisco_info: "{{ decoded_file | regex_search('(?i)^cisco\\s' ~ switch_model ~ '.*(?:\\n(?!\\s*$).*)*', multiline=True) | split('\n') }}"

    # - name: Print Switch Model
    #   debug:
    #     msg: "Switch Model: {{ switch_model }}"

    # - name: Print Board ID
    #   debug:
    #     msg: "Board ID: {{ board_id }}"

    # - name: Print Uptime Info
    #   debug:
    #     msg: "Uptime Info: {{ uptime_info }}"

    # - name: Print Hostname
    #   debug:
    #     msg: "Hostname: {{ hostname }}"

    # - name: Print VLAN IP
    #   debug:
    #     msg: "VLAN IP: {{ vlan_ip }}"

    # - name: Print Switch Version
    #   debug:
    #     msg: "SW Version: {{ switch_version }}"

    # - name: Print System Image
    #   debug:
    #     msg: "System Image: {{ system_image }}"

    # - name: Print CPU Utilization
    #   debug:
    #     msg: "CPU Utilization: {{ cpu_util }}"